### ISSUE TITLE
Inspector

### ISSUE THREAD

**Issue by sythang2503** [nhonan2000/baitap1#2]
Mọi người thảo luận đi

**Comment by nhonan2000** [comment]
hello :v

**Comment by DinhHau09** [comment]
Theo cá nhân của mình thấy thì phần hàm phép chia thiếu điều kiện "không được chia cho 0" .

**Comment by vohongquang** [comment]
Theo mình thì phầm giao diện chữ Máy tính cho cỡ chữ lớn hơm xíu , các nút button cộng trù nhân chia thì thêm màu vào cho button và thêm 1 button thoát sau khi thực hiện song phép tính

**Comment by nhonan2000** [comment]
> Theo cá nhân mình thấy thì thiếu điều kiện chia thành phần "not be shared for 0".

Ok, mình sẽ thêm vào

**Comment by nhonan2000** [comment]
> Theo mình thì phầm máy giao diện chữ to cỡ chữ hơm, các nút bấm cộng thêm nhân chia, thêm màu vào nút và thêm 1 nút thoát sau khi thực hiện bài hát được phép tính

mình đồng ý với ý kiến điều chỉnh cỡ chữ của bạn. về thêm màu vào các nút button thì không cần thiết và thêm nút button thoát cũng không cần thiết vì nó đã có sẵn rồi.

**Comment by sythang2503** [comment]
> Theo cá nhân của mình thấy thì phần hàm phép chia thiếu điều kiện "không được chia cho 0"
Mình cũng đồng ý

**Comment by sythang2503** [comment]
> Theo cá nhân của mình thấy thì phần hàm phép chia thiếu điều kiện "không được chia cho 0" .

**Comment by huadaivuong** [comment]
Theo cá nhân của mình thấy phần output nên chia ra giữa phần tính và phần kết quả và cho chúng vào khung

**Comment by nhonan2000** [comment]
> Theo cá nhân của mình thấy phần output nên chia ra giữa phần tính và phần kết quả và cho chúng vào khung

Ok, mình sẽ sửa lại

**Comment by huadaivuong** [comment]
phần chữ "Kết Quả" nên in đậm và có cỡ chữ to hơn thì sẽ hợp lí

**Comment by sythang2503** [comment]
mọi người xem tiếp phần code đi
